### ISSUE TITLE
Adding heatmap generation for non siglip models like vidore/colqwen2-v0.1

### ISSUE THREAD

**Issue by AlexAndrei98** [tonywu71/colpali-cookbooks#4]
I believe since Qwen can take arbitrary size images the rearranging is going to be slightly different.  
I tried for an hour but wouldn't figure it out, any pointers would be helpful and can create a PR.

**Comment by tonywu71** [comment]
Hi @AlexAndrei98! You're right, the rearranging will indeed differ. From a quick look at the code, [this code](https://github.com/illuin-tech/vidore-benchmark/blob/c217f5285c3edc7efedc8221db00e7160537c70b/src/vidore_benchmark/interpretability/gen_similarity_maps.py#L75C1-L78C44) will have to be modified:

```python
    # Rearrange the output image tensor to explicitly represent the 2D grid of patches
    output_image = rearrange(
        output_image, "b (h w) c -> b h w c", h=vit_config.n_patch_per_dim, w=vit_config.n_patch_per_dim
    )  # (1, n_patches_x, n_patches_y, dim)
```

From a quick look at it, you would have to replace the values of `h` and `w` depending on your input image size. The "Naive Dynamic Resolution" of the [Qwen2-VL paper](https://arxiv.org/abs/2409.12191) is a good resource to do that.

If you're interested into contributing, could you wait for a few days? 👋🏼 I want to first move the interpretability code from [vidore-benchmark](https://github.com/illuin-tech/vidore-benchmark) to [colpali-engine](https://github.com/illuin-tech/colpali) to address https://github.com/illuin-tech/colpali/issues/81. I'll ping you once I'll be done with it!

**Comment by tonywu71** [comment]
@AlexAndrei98 FYI I've just merged https://github.com/illuin-tech/colpali/pull/96 to add similarity map support for ColQwen2 👍🏼
